- name: Disable builtin networking
  ansible.builtin.replace:
    path: /etc/network/interfaces
    regexp: '^[^#](.*ens192.*)'
    replace: '#\1'

- name: Enable systemd networking
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: ["systemd-networkd", "systemd-resolved"]

- name: Systemd network file
  ansible.builtin.template:
    src: 10-IT.network.j2
    dest: /etc/systemd/network/10-IT.network
    owner: root
    group: root
    mode: '0644'

- name: Get resolv.conf info
  ansible.builtin.stat:
    path: /etc/resolv.conf
  register: common_networking_r

- name: Delete old resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  when: not common_networking_r.stat.islnk

- name: Setup systemd-resolved
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
