#!/bin/bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/scripts/installer_util.sh"

SAFE=true
while getopts "u" o; do
    case ${o} in
    u)
        SAFE=false
        ;;
    esac
done

install_apps
install_scripts
install_dotfiles $SAFE
