#!/bin/bash

# DIR="${BASH_SOURCE%/*}"
# if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "/home/$(whoami)/.dotfiles/lib/installer-util.sh"

SAFE=true
while getopts "u" o; do
    case ${o} in
    u)
        SAFE=false
        ;;
    esac
done

install_dotfiles $SAFE
install_scripts
install_plugins
