#!/bin/bash

OTHER_FILES="viminfo zcompdump zhistory zsh_history"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for item in $DIR/conf/*; do
    if [[ -L "$HOME/.${item##*/}" ]]; then
        rm -rf $HOME/.${item##*/}
    fi
done

# for item in $OTHER_FILES; do
#     if [[ -e "$HOME/.$item" ]]; then
#         rm -rf "$HOME/.$item"
#     fi
# done

for item in $DIR/scripts/*; do
    if [[ -L "$HOME/bin/${item##*/}" ]]; then
        rm $HOME/bin/${item##*/}
    fi
done

if [[ -L "$HOME/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings" ]]; then
    rm "$HOME/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
    mv "$HOME/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings.old" "$HOME/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
fi
