- name: Download minikube
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
    dest: /tmp/minikube_latest_amd64.deb
    mode: '0644'

- name: Install minikube
  ansible.builtin.apt:
    deb: /tmp/minikube_latest_amd64.deb
