---
- name: install repo deps
  apt:
    pkg:
    - apt-transport-https
    - software-properties-common
    - wget
    update_cache: yes

- name: add grafana apt key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    state: present

- name: install grafana enterprise
  apt:
    name: grafana-enterprise
    update_cache: yes
    state: present
