if hash "pyenv" 2> /dev/null; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path --no-rehash)"
fi

# vim: ai et nu ts=4 sw=4 sts=4 ft=sh :
