export TERM=xterm-256color
export VISUAL=vim
export EDITOR=$VISUAL

# Aliases
[[ -f ~/.aliases ]] && . ~/.aliases

OS=`uname | tr "A-Z" "a-z"`
case $OS in
"darwin")
    path=(
        $HOME/bin
        $HOME/.local/bin
        $HOME/.cargo/bin
        /opt/homebrew/opt/coreutils/libexec/gnubin
        /opt/homebrew/opt/make/libexec/gnubin
        /Library/TeX/texbin
        /usr/local/sbin
        /usr/sbin
        /sbin
        /usr/local/bin
        /usr/bin
        /bin
    )
    ;;
"linux")
    path=(
        $HOME/bin
        /usr/local/sbin
        /usr/sbin
        /sbin
        /usr/local/bin
        /usr/bin
        /bin
    )
    ;;
esac

# vim: ai et nu ts=4 sw=4 sts=4 ft=sh :
