# Add local path to custom themes and functions
fpath=(
    ~/.zsh/site-functions
    $fpath
)

if [[ ! -e $HOME/.znap/zsh-snap ]]; then
   mkdir -p $HOME/.znap
   git clone https://github.com/marlonrichert/zsh-snap $HOME/.znap/zsh-snap
fi

#if [[ ! -e ~/.vim/bundle/Vundle.vim ]]; then
#    mkdir -p ~/.vim/bundle
#    git clone https://github.com/VundleVim/Vundle.vim ~/.vim/bundle/Vundle.vim
#    vim -u ~/.vimrc +VundleInstall +qall
#fi

if hash "neofetch" 2> /dev/null; then
   neofetch
fi

# Standard emacs keymap
bindkey -e

source $HOME/.znap/zsh-snap/znap.zsh

znap prompt cook

#znap source marlonrichert/zsh-autocomplete
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap source chriskempson/base16-shell

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
   [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
       eval "$("$BASE16_SHELL/profile_helper.sh")"

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory


if ! hash "nvm" 2> /dev/null; then
    if [ ! -d "$HOME/.nvm" ]; then
        git clone https://github.com/nvm-sh/nvm.git .nvm
    fi

    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi

if ! hash "pyenv" 2> /dev/null; then
    if [ ! -d "$HOME/.pyenv" ]; then
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv
        pushd $HOME/.pyenv
        src/configure && make -C src
        popd
    fi

    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
fi

if hash "direnv" 2> /dev/null; then
    eval "$(direnv hook zsh)"
fi

if [ -e "$HOME/.cargo/env" ]; then
    source "$HOME/.cargo/env"
fi

# vim: ai et nu ts=4 sw=4 sts=4 ft=sh :
