# Options
OPTION_PLUGINS="T"
OPTION_PROMPT="T"
OPTION_NEOFETCH="F"

# Configuration
ENABLE_PYENV="F"
ENABLE_CARGO="T"
ENABLE_NVM="F"
ENABLE_DIRENV="F"
ENABLE_KEYCHAIN="F"

# Configurations
CONFIG_TMUX="T"
CONFIG_ITERM2="T"

# Add local path to custom themes and functions
fpath=(
    ~/.zsh/site-functions
    $fpath
)

if [[ ! -e $HOME/.znap/zsh-snap ]]; then
   mkdir -p $HOME/.znap
   git clone https://github.com/marlonrichert/zsh-snap $HOME/.znap/zsh-snap
fi

if [ "$OPTION_NEOFETCH" = "T" ]; then
    if hash "neofetch" 2> /dev/null; then
       neofetch
    fi
fi

# Standard emacs keymap
bindkey -e

if [ "$OPTION_PLUGINS" = "T" ]; then
    source $HOME/.znap/zsh-snap/znap.zsh

    znap source marlonrichert/zsh-autocomplete
    znap source zsh-users/zsh-autosuggestions
    znap source zsh-users/zsh-syntax-highlighting
fi

if [ "$OPTION_PROMPT" = "T" ]; then
    znap prompt cook
fi

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory

if [ "$ENABLE_NVM" = "T" ]; then
    if ! hash "nvm" 2> /dev/null; then
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    fi
fi

if [ "$ENABLE_PYENV" = "T" ]; then
    if hash "pyenv" 2> /dev/null; then
        export PYENV_ROOT="/opt/homebrew/opt/pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        znap eval "$(pyenv init -)"
        znap eval "$(pyenv virtualenv-init -)"
    fi
fi

if [ "$ENABLE_CARGO" = "T" ]; then
    if [ -e "$HOME/.cargo/env" ]; then
        source "$HOME/.cargo/env"
    fi
fi

if [ "$ENABLE_DIRENV" = "T" ]; then
    if hash "direnv" 2> /dev/null; then
        eval "$(direnv hook zsh)"
    fi
fi

if [ "$ENABLE_KEYCHAIN" = "T" ]; then
    if hash "keychain" 2> /dev/null; then
        keychain id_ed25519
        [ -z "$HOSTNAME" ] && HOSTNAME=`uname -n`
        [ -f $HOME/.keychain/$HOSTNAME-sh ] && . $HOME/.keychain/$HOSTNAME-sh
    fi
fi

if [ "$CONFIG_TMUX" = "T" ]; then
    if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    fi
fi

if [ "$CONFIG_ITERM2" = "T" ]; then
    test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

# vim: ai et nu ts=4 sw=4 sts=4 ft=sh :
