---
- name: Install docker dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: ["ca-certificates", "curl", "gnupg", "lsb-release"]

- name: Test if gpg key exists
  ansible.builtin.stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker_main_gpgkey

- name: Download docker repo gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /tmp/docker.gpg
    mode: '0644'
  when: not docker_main_gpgkey.stat.exists

- name: Dearmor gpg key
  ansible.builtin.shell: |
    set -o pipefail
    install -m 0755 -d /etc/apt/keyrings
    cat /tmp/docker.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
    executable: /bin/bash
  when: not docker_main_gpgkey.stat.exists

- name: Install docker repo
  ansible.builtin.copy:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: '0644'

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin']

- name: Add user to docker group
  ansible.builtin.user:
    name: kcook
    groups: docker
    append: true
