Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provision "shell", inline: <<-SCRIPT
#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
APT=/usr/bin/apt-get

$APT -y update && $APT -y upgrade && $APT -y dist-upgrade

$APT install -y build-essential gcc gdb nasm \
    valgrind cmake manpages-posix-dev \
    flex bison \
    libssl-dev libelf-dev \
    llvm clang
SCRIPT
  config.vm.provision :reload

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["numvcpus"] = "4"
    v.vmx["memsize"] = "8196"
  end
end
