# Update the current state of the XDG config directories
xdg-user-dirs-update

# Disable terminal bell
xset -b

# Disable screen timeouts
xset s off

# Disable screen power management
xset -dpms

# Save state of numlock
numlockx

# Map caps lock to escape
setxkbmap -option caps:escape

# Allow ctrl-alt-backspace to restart the X server
setxkbmap -option terminate:ctrl_alt_bksp

# Execute any xinitrc scripts from the system
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Run Xresources configuration
xrdb -merge ~/.Xresources

# Gnome keyring for session/key management
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# Start i3
exec /usr/sbin/i3 -V >> ~/.config/i3/logfile
